export const AUTH_CREATE_SUCCESS = "AUTH_CREATE_SUCCESS";
export const AUTH_CREATE_FAILURE = "AUTH_CREATE_FAILURE";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const CURRENT_USER_DATA = "CURRENT_USER_DATA";